# Generated by Django 6.0.7 on 2026-07-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="Employee1",
        ),
    ]
