# Generated by Django 6.0.7 on 2026-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0003_product_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_placeholder_tone",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
