# Generated by Django 6.0.7 on 2026-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0004_remove_product_image_placeholder_tone_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/images"),
        ),
    ]
