# Generated by Django 6.0.7 on 2026-08-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0005_alter_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
