# Generated by Django 6.0.7 on 2026-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0006_delete_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
    ]
