# Generated by Django 6.0.7 on 2026-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0007_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
