# Generated by Django 6.0.7 on 2026-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0010_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_trashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_trashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
