# Generated by Django 6.0.7 on 2026-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0011_category_is_trashed_category_trashed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
