# Generated by Django 6.0.7 on 2026-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBstore", "0012_product_offer_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="purchase",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
